---
- name: "Installer serveur apache"
  apt:
          name: apache2.4.29
          state: present


- name: "Copier le template de conf apache dans le conteneur"
  template:
          src: 'templates/apache2.conf.j2'
          dest: '/etc/apache2/apache.conf'
  notify:
          - Restart Apache

- name: "Démarrer apache si ce n'est pas fait"
  service:
          name: apache2
          state: started

