---
- hosts: webserver
  remote_user: root
  vars_files:
          - "vars/{{env}}_vars.yml"
          - "vars/{{env}}_secret.yml"

  roles:
          - { role: Apache }
          - { role: Php }
          - { role: Mysql }

