--- 
- name: "Installer serveur apache"
  apt:
          name: apache2
          state: present

- name: "Copy le fichier test.txt dans le conteneur"
  copy:
          src: 'files/test.txt'
          dest: '/tmp/test.txt'

- name: "Copier le template index.html pour le site du conteneur"
  template:
          src: 'templates/index.html.j2'
          dest: '/var/www/html/index.html'
  notify:
          - Restart Apache

- name: "Démarrer apache si ce n'est pas fait"
  service:
          name: apache2
          state: started

